import "../styles/globals.scss";
// import { Inter } from "next/font/google";
import { LayoutProvider } from "./LayoutProvider";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scott",
  description: "Generated by....",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <body className={inter.className}> */}
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
