import MobileNav from "@/components/MobileNav";
import "../styles/globals.scss";
// import { LayoutProvider } from "./LayoutProvider";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Scott",
  description: "Generated by....",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MobileNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
