const photos = [
  {
    format: "jpeg",
    width: 5616,
    height: 3744,
    filename: "0000_yC-Yzbqy7PY.jpeg",
    id: 0,
    author: "Alejandro Escamilla",
    author_url: "https://unsplash.com/@alejandroescamilla",
    post_url: "https://unsplash.com/photos/yC-Yzbqy7PY",
  },
  {
    format: "jpeg",
    width: 5616,
    height: 3744,
    filename: "0001_LNRyGwIJr5c.jpeg",
    id: 1,
    author: "Alejandro Escamilla",
    author_url: "https://unsplash.com/@alejandroescamilla",
    post_url: "https://unsplash.com/photos/LNRyGwIJr5c",
  },
  {
    format: "jpeg",
    width: 5616,
    height: 3744,
    filename: "0002_N7XodRrbzS0.jpeg",
    id: 2,
    author: "Alejandro Escamilla",
    author_url: "https://unsplash.com/@alejandroescamilla",
    post_url: "https://unsplash.com/photos/N7XodRrbzS0",
  },
  {
    format: "jpeg",
    width: 5616,
    height: 3744,
    filename: "0003_Dl6jeyfihLk.jpeg",
    id: 3,
    author: "Alejandro Escamilla",
    author_url: "https://unsplash.com/@alejandroescamilla",
    post_url: "https://unsplash.com/photos/Dl6jeyfihLk",
  },
  {
    format: "jpeg",
    width: 5616,
    height: 3744,
    filename: "0004_y83Je1OC6Wc.jpeg",
    id: 4,
    author: "Alejandro Escamilla",
    author_url: "https://unsplash.com/@alejandroescamilla",
    post_url: "https://unsplash.com/photos/y83Je1OC6Wc",
  },
  {
    format: "jpeg",
    width: 5245,
    height: 3497,
    filename: "0005_LF8gK8-HGSg.jpeg",
    id: 5,
    author: "Alejandro Escamilla",
    author_url: "https://unsplash.com/@alejandroescamilla",
    post_url: "https://unsplash.com/photos/LF8gK8-HGSg",
  },
];

export { photos };
